// This file was generated by Peginator v0.3.0
// Hash of the grammar file: EAD9CA499B62A4A1FC52025C73572E003A2098C3BBDDDA1F2076CD7945BDD22A
// Any changes to it will be lost on regeneration

#[derive(Debug, Clone)]
pub struct ProgramParser {
    pub program: ProgramNode,
}
#[derive(Debug, Clone)]
pub struct ProgramNode {
    pub statements: Vec<StatementNode>,
    pub position: std::ops::Range<usize>,
}
#[allow(non_camel_case_types)]
#[derive(Debug, Clone)]
pub enum StatementNode {
    DefineStatement(DefineStatement),
    EmptyStatement(EmptyStatement),
}
#[derive(Debug, Clone)]
pub struct EmptyStatement;
pub type EOS = char;
#[derive(Debug, Clone)]
pub struct DefineStatement {
    pub define: DEFINE,
    pub modifiers: Modifiers,
    pub symbol: Identifier,
    pub arguments: Option<Arguments>,
    pub r#type: Option<Typing>,
    pub body: ChoiceNode,
    pub position: std::ops::Range<usize>,
}
pub type DEFINE = String;
#[derive(Debug, Clone)]
pub struct MacroCalls {
    pub macros: Vec<Macro>,
}
#[derive(Debug, Clone)]
pub struct Macro {
    pub id: Identifier,
    pub args: Option<ArgumentValue>,
}
pub type Boolean = String;
pub type ArgumentValue = String;
#[derive(Debug, Clone)]
pub struct Modifiers {
    pub id: Vec<Identifier>,
    pub position: std::ops::Range<usize>,
}
#[derive(Debug, Clone)]
pub struct ChoiceNode {
    pub terms: Vec<TermStream>,
    pub position: std::ops::Range<usize>,
}
#[allow(non_camel_case_types)]
#[derive(Debug, Clone)]
pub enum ExprStream {
    CharsetNode(CharsetNode),
    Group(Group),
    Identifier(Identifier),
    Infix(Infix),
    Prefix(Prefix),
    StringLiteral(StringLiteral),
    Suffix(Suffix),
}
pub type Prefix = char;
pub type Suffix = char;
pub type Infix = char;
#[derive(Debug, Clone)]
pub struct Arguments {
    pub position: std::ops::Range<usize>,
}
#[derive(Debug, Clone)]
pub struct Typing {
    pub id: Identifier,
    pub position: std::ops::Range<usize>,
}
#[derive(Debug, Clone)]
pub struct Group {
    pub body: ChoiceNode,
    pub position: std::ops::Range<usize>,
}
#[derive(Debug, Clone)]
pub struct StringLiteral {
    pub body: Vec<StringItem>,
    pub position: std::ops::Range<usize>,
}
#[allow(non_camel_case_types)]
#[derive(Debug, Clone)]
pub enum StringItem {
    CharOne(CharOne),
    StringEscaped(StringEscaped),
}
#[derive(Debug, Clone)]
pub struct StringEscaped {
    pub char: char,
}
#[derive(Debug, Clone)]
pub struct CharsetNode {
    pub neg: Option<CharsetNeg>,
    pub items: Vec<CharItem>,
    pub position: std::ops::Range<usize>,
}
#[derive(Debug, Clone)]
pub struct CharsetNeg;
#[allow(non_camel_case_types)]
#[derive(Debug, Clone)]
pub enum CharItem {
    CharOne(CharOne),
    CharRange(CharRange),
}
#[derive(Debug, Clone)]
pub struct CharRange {
    pub start: char,
    pub end: char,
    pub position: std::ops::Range<usize>,
}
pub type CharOne = char;
#[derive(Debug, Clone)]
pub struct Identifier {
    pub string: String,
    pub position: std::ops::Range<usize>,
}
pub type XID_START = char;
pub type XID_CONTINUE = char;
impl peginator_generated::PegParser for ProgramParser {
    fn parse_advanced<T: peginator_generated::ParseTracer>(
        s: &str,
        settings: &peginator_generated::ParseSettings,
    ) -> Result<Self, peginator_generated::ParseError> {
        Ok(peginator_generated::parse_ProgramParser(
            peginator_generated::ParseState::new(s, settings),
            T::new(),
            &mut Default::default(),
        )?
        .result)
    }
}
#[allow(non_snake_case, unused_variables, unused_imports, unused_mut, dead_code)]
mod peginator_generated {
    use super::*;
    use peginator::runtime::*;
    pub use peginator::runtime::{IndentedTracer, ParseError, ParseSettings, ParseState, ParseTracer, PegParser, PegPosition};
    #[derive(Default)]
    pub struct ParseCache<'a> {
        _please_dont_complain: std::marker::PhantomData<&'a ()>,
    }
    mod ProgramParser_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let ParseOk { result: program, state } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_ProgramNode(state, tracer, cache))?;
            let ParseOk { state, .. } =
                parse_Whitespace(state, tracer, cache).and_then(|ParseOk { state, .. }| parse_end_of_input(state))?;
            Ok(ParseOk { result: program, state })
        }
        pub type Parsed = ProgramNode;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::ProgramParser> {
            let result = parse(state, tracer, cache)?.map(|r| super::ProgramParser { program: r });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_ProgramParser<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, ProgramParser> {
        tracer.run_traced("ProgramParser", state, |state, tracer| ProgramParser_impl::rule_parser(state, tracer, cache))
    }
    mod ProgramNode_impl {
        use super::*;
        mod closure {
            use super::*;
        }
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let mut iterations: usize = 0;
            let mut state = state;
            let mut statements: Vec<StatementNode> = Vec::new();
            loop {
                match parse_Whitespace(state.clone(), tracer, cache)
                    .and_then(|ParseOk { state, .. }| parse_StatementNode(state, tracer, cache))
                    .map_inner(|result| vec![result])
                {
                    Ok(ParseOk { result: __result, state: new_state, .. }) => {
                        statements.extend(__result);
                        state = new_state;
                    }
                    Err(err) => {
                        state = state.record_error(err);
                        break;
                    }
                }
                iterations += 1;
            }
            Ok(ParseOk { result: statements, state })
        }
        pub type Parsed = Vec<StatementNode>;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::ProgramNode> {
            let result = parse(state.clone(), tracer, cache)?
                .map_with_state(|r, new_state| super::ProgramNode { statements: r, position: state.range_until(new_state) });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_ProgramNode<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, ProgramNode> {
        tracer.run_traced("ProgramNode", state, |state, tracer| ProgramNode_impl::rule_parser(state, tracer, cache))
    }
    impl PegPosition for ProgramNode {
        fn position(&self) -> &std::ops::Range<usize> {
            &self.position
        }
    }
    mod StatementNode_impl {
        use super::*;
        mod choice_0 {
            use super::*;
            #[inline(always)]
            pub fn parse<'a>(
                state: ParseState<'a>,
                tracer: impl ParseTracer,
                cache: &mut ParseCache<'a>,
            ) -> ParseResult<'a, Parsed> {
                let ParseOk { result: _override, state } = parse_Whitespace(state, tracer, cache)
                    .and_then(|ParseOk { state, .. }| parse_DefineStatement(state, tracer, cache))
                    .map_inner(Parsed__override::DefineStatement)?;
                let ParseOk { state, .. } = parse_Whitespace(state.clone(), tracer, cache)
                    .and_then(|ParseOk { state, .. }| parse_EOS(state, tracer, cache))
                    .discard_result()
                    .or_else(|err| Ok(ParseOk { result: (), state: state.record_error(err) }))?;
                Ok(ParseOk { result: _override, state })
            }
            pub type Parsed = Parsed__override;
        }
        #[inline(always)]
        pub fn parse<'a>(
            mut state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            ChoiceHelper::new(state)
                .choice(|state| choice_0::parse(state.clone(), tracer, cache))
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_EmptyStatement(state, tracer, cache))
                        .map_inner(Parsed__override::EmptyStatement)
                })
                .end()
        }
        pub type Parsed = Parsed__override;
        use super::StatementNode as Parsed__override;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::StatementNode> {
            let result = parse(state, tracer, cache)?;
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_StatementNode<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, StatementNode> {
        tracer.run_traced("StatementNode", state, |state, tracer| StatementNode_impl::rule_parser(state, tracer, cache))
    }
    mod EmptyStatement_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_EOS(state, tracer, cache))
                .discard_result()
        }
        pub type Parsed = ();
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::EmptyStatement> {
            let result = parse(state, tracer, cache)?.map(|r| super::EmptyStatement {});
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_EmptyStatement<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, EmptyStatement> {
        tracer.run_traced("EmptyStatement", state, |state, tracer| EmptyStatement_impl::rule_parser(state, tracer, cache))
    }
    #[inline]
    pub(super) fn parse_EOS<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, EOS> {
        if let Ok(result) = parse_character_literal(state.clone(), ';') {
            return Ok(result);
        }
        Err(state.report_error(ParseErrorSpecifics::ExpectedCharacterClass { name: "EOS" }))
    }
    mod DefineStatement_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_MacroCalls(state, tracer, cache))
                .discard_result()?;
            let ParseOk { result: define, state } =
                parse_Whitespace(state, tracer, cache).and_then(|ParseOk { state, .. }| parse_DEFINE(state, tracer, cache))?;
            let ParseOk { result: modifiers, state } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_Modifiers(state, tracer, cache))?;
            let ParseOk { result: symbol, state } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_Identifier(state, tracer, cache))?;
            let ParseOk { result: arguments, state } = parse_Whitespace(state.clone(), tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_Arguments(state, tracer, cache))
                .map_inner(Some)
                .or_else(|err| Ok(ParseOk { result: Default::default(), state: state.record_error(err) }))?;
            let ParseOk { result: r#type, state } = parse_Whitespace(state.clone(), tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_Typing(state, tracer, cache))
                .map_inner(Some)
                .or_else(|err| Ok(ParseOk { result: Default::default(), state: state.record_error(err) }))?;
            let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, '{'))
                .discard_result()?;
            let ParseOk { result: body, state } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_ChoiceNode(state, tracer, cache))?;
            let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, '}'))
                .discard_result()?;
            Ok(ParseOk { result: Parsed { define, modifiers, symbol, arguments, r#type, body }, state })
        }
        pub struct Parsed {
            pub define: DEFINE,
            pub modifiers: Modifiers,
            pub symbol: Identifier,
            pub arguments: Option<Arguments>,
            pub r#type: Option<Typing>,
            pub body: ChoiceNode,
        }
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::DefineStatement> {
            let result = parse(state.clone(), tracer, cache)?.map_with_state(|r, new_state| super::DefineStatement {
                define: r.define,
                modifiers: r.modifiers,
                symbol: r.symbol,
                arguments: r.arguments,
                r#type: r.r#type,
                body: r.body,
                position: state.range_until(new_state),
            });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_DefineStatement<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, DefineStatement> {
        tracer.run_traced("DefineStatement", state, |state, tracer| DefineStatement_impl::rule_parser(state, tracer, cache))
    }
    impl PegPosition for DefineStatement {
        fn position(&self) -> &std::ops::Range<usize> {
            &self.position
        }
    }
    mod DEFINE_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            mut state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            ChoiceHelper::new(state)
                .choice(|state| parse_string_literal(state, "def!").discard_result())
                .choice(|state| parse_string_literal(state, "def").discard_result())
                .end()
        }
        pub type Parsed = ();
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, DEFINE> {
            let result = parse(state.clone(), tracer, cache)?.map_with_state(|_, new_state| {
                let string = state.slice_until(new_state).to_string();
                string
            });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_DEFINE<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, DEFINE> {
        tracer.run_traced("DEFINE", state, |state, tracer| DEFINE_impl::rule_parser(state, tracer, cache))
    }
    mod MacroCalls_impl {
        use super::*;
        mod closure {
            use super::*;
            mod choice_0 {
                use super::*;
                #[inline(always)]
                pub fn parse<'a>(
                    state: ParseState<'a>,
                    tracer: impl ParseTracer,
                    cache: &mut ParseCache<'a>,
                ) -> ParseResult<'a, Parsed> {
                    let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_character_literal(state, '#'))
                        .discard_result()?;
                    let ParseOk { result: mut macros, state } = parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_Macro(state, tracer, cache))
                        .map_inner(|result| vec![result])?;
                    Ok(ParseOk { result: macros, state })
                }
                pub type Parsed = Vec<Macro>;
            }
            mod choice_1 {
                use super::*;
                #[inline(always)]
                pub fn parse<'a>(
                    state: ParseState<'a>,
                    tracer: impl ParseTracer,
                    cache: &mut ParseCache<'a>,
                ) -> ParseResult<'a, Parsed> {
                    let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_character_literal(state, '#'))
                        .discard_result()?;
                    let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_character_literal(state, '['))
                        .discard_result()?;
                    let ParseOk { result: mut macros, state } = parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_Macro(state, tracer, cache))
                        .map_inner(|result| vec![result])?;
                    let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_character_literal(state, ']'))
                        .discard_result()?;
                    Ok(ParseOk { result: macros, state })
                }
                pub type Parsed = Vec<Macro>;
            }
            #[inline(always)]
            pub fn parse<'a>(
                mut state: ParseState<'a>,
                tracer: impl ParseTracer,
                cache: &mut ParseCache<'a>,
            ) -> ParseResult<'a, Parsed> {
                ChoiceHelper::new(state)
                    .choice(|state| choice_0::parse(state.clone(), tracer, cache))
                    .choice(|state| choice_1::parse(state.clone(), tracer, cache))
                    .end()
            }
            pub type Parsed = Vec<Macro>;
        }
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let mut iterations: usize = 0;
            let mut state = state;
            let mut macros: Vec<Macro> = Vec::new();
            loop {
                match closure::parse(state.clone(), tracer, cache) {
                    Ok(ParseOk { result: __result, state: new_state, .. }) => {
                        macros.extend(__result);
                        state = new_state;
                    }
                    Err(err) => {
                        state = state.record_error(err);
                        break;
                    }
                }
                iterations += 1;
            }
            Ok(ParseOk { result: macros, state })
        }
        pub type Parsed = Vec<Macro>;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::MacroCalls> {
            let result = parse(state, tracer, cache)?.map(|r| super::MacroCalls { macros: r });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_MacroCalls<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, MacroCalls> {
        tracer.run_traced("MacroCalls", state, |state, tracer| MacroCalls_impl::rule_parser(state, tracer, cache))
    }
    mod Macro_impl {
        use super::*;
        mod part_1 {
            use super::*;
            mod optional {
                use super::*;
                #[inline(always)]
                pub fn parse<'a>(
                    state: ParseState<'a>,
                    tracer: impl ParseTracer,
                    cache: &mut ParseCache<'a>,
                ) -> ParseResult<'a, Parsed> {
                    let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_character_literal(state, '('))
                        .discard_result()?;
                    let ParseOk { result: args, state } = parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_ArgumentValue(state, tracer, cache))
                        .map_inner(Some)?;
                    let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_character_literal(state, ')'))
                        .discard_result()?;
                    Ok(ParseOk { result: args, state })
                }
                pub type Parsed = Option<ArgumentValue>;
            }
            #[inline(always)]
            pub fn parse<'a>(
                state: ParseState<'a>,
                tracer: impl ParseTracer,
                cache: &mut ParseCache<'a>,
            ) -> ParseResult<'a, Parsed> {
                optional::parse(state.clone(), tracer, cache)
                    .or_else(|err| Ok(ParseOk { result: Default::default(), state: state.record_error(err) }))
            }
            pub type Parsed = Option<ArgumentValue>;
        }
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let ParseOk { result: id, state } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_Identifier(state, tracer, cache))?;
            let ParseOk { result: args, state } = part_1::parse(state, tracer, cache)?;
            Ok(ParseOk { result: Parsed { id, args }, state })
        }
        pub struct Parsed {
            pub id: Identifier,
            pub args: Option<ArgumentValue>,
        }
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::Macro> {
            let result = parse(state, tracer, cache)?.map(|r| super::Macro { id: r.id, args: r.args });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_Macro<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, Macro> {
        tracer.run_traced("Macro", state, |state, tracer| Macro_impl::rule_parser(state, tracer, cache))
    }
    mod Boolean_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            mut state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            ChoiceHelper::new(state)
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_string_literal(state, "true"))
                        .discard_result()
                })
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_string_literal(state, "false"))
                        .discard_result()
                })
                .end()
        }
        pub type Parsed = ();
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Boolean> {
            let result = parse(state.clone(), tracer, cache)?.map_with_state(|_, new_state| {
                let string = state.slice_until(new_state).to_string();
                string
            });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_Boolean<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, Boolean> {
        tracer.run_traced("Boolean", state, |state, tracer| Boolean_impl::rule_parser(state, tracer, cache))
    }
    mod ArgumentValue_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            parse_Whitespace(state, tracer, cache).and_then(|ParseOk { state, .. }| parse_Boolean(state, tracer, cache))
        }
        pub type Parsed = Boolean;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, ArgumentValue> {
            let result = parse(state.clone(), tracer, cache)?.map_with_state(|_, new_state| {
                let string = state.slice_until(new_state).to_string();
                string
            });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_ArgumentValue<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, ArgumentValue> {
        tracer.run_traced("ArgumentValue", state, |state, tracer| ArgumentValue_impl::rule_parser(state, tracer, cache))
    }
    mod Modifiers_impl {
        use super::*;
        mod closure {
            use super::*;
            mod part_1 {
                use super::*;
                mod negative_lookahead {
                    use super::*;
                    #[inline(always)]
                    pub fn parse<'a>(
                        mut state: ParseState<'a>,
                        tracer: impl ParseTracer,
                        cache: &mut ParseCache<'a>,
                    ) -> ParseResult<'a, Parsed> {
                        ChoiceHelper::new(state)
                            .choice(|state| {
                                parse_Whitespace(state, tracer, cache)
                                    .and_then(|ParseOk { state, .. }| parse_character_literal(state, '{'))
                                    .discard_result()
                            })
                            .choice(|state| {
                                parse_Whitespace(state, tracer, cache)
                                    .and_then(|ParseOk { state, .. }| parse_character_literal(state, '('))
                                    .discard_result()
                            })
                            .choice(|state| {
                                parse_Whitespace(state, tracer, cache)
                                    .and_then(|ParseOk { state, .. }| parse_character_literal(state, ':'))
                                    .discard_result()
                            })
                            .choice(|state| {
                                parse_Whitespace(state, tracer, cache)
                                    .and_then(|ParseOk { state, .. }| parse_string_literal(state, "->"))
                                    .discard_result()
                            })
                            .choice(|state| {
                                parse_Whitespace(state, tracer, cache)
                                    .and_then(|ParseOk { state, .. }| parse_character_literal(state, ';'))
                                    .discard_result()
                            })
                            .end()
                    }
                    pub type Parsed = ();
                }
                #[inline(always)]
                pub fn parse<'a>(
                    state: ParseState<'a>,
                    tracer: impl ParseTracer,
                    cache: &mut ParseCache<'a>,
                ) -> ParseResult<'a, Parsed> {
                    match negative_lookahead::parse(state.clone(), tracer, cache) {
                        Ok(_) => Err(state.report_error(ParseErrorSpecifics::NegativeLookaheadFailed)),
                        Err(_) => Ok(ParseOk { result: (), state }),
                    }
                }
                pub type Parsed = ();
            }
            #[inline(always)]
            pub fn parse<'a>(
                state: ParseState<'a>,
                tracer: impl ParseTracer,
                cache: &mut ParseCache<'a>,
            ) -> ParseResult<'a, Parsed> {
                let ParseOk { result: mut id, state } = parse_Whitespace(state, tracer, cache)
                    .and_then(|ParseOk { state, .. }| parse_Identifier(state, tracer, cache))
                    .map_inner(|result| vec![result])?;
                let ParseOk { state, .. } = part_1::parse(state, tracer, cache)?;
                Ok(ParseOk { result: id, state })
            }
            pub type Parsed = Vec<Identifier>;
        }
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let mut iterations: usize = 0;
            let mut state = state;
            let mut id: Vec<Identifier> = Vec::new();
            loop {
                match closure::parse(state.clone(), tracer, cache) {
                    Ok(ParseOk { result: __result, state: new_state, .. }) => {
                        id.extend(__result);
                        state = new_state;
                    }
                    Err(err) => {
                        state = state.record_error(err);
                        break;
                    }
                }
                iterations += 1;
            }
            Ok(ParseOk { result: id, state })
        }
        pub type Parsed = Vec<Identifier>;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::Modifiers> {
            let result = parse(state.clone(), tracer, cache)?
                .map_with_state(|r, new_state| super::Modifiers { id: r, position: state.range_until(new_state) });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_Modifiers<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, Modifiers> {
        tracer.run_traced("Modifiers", state, |state, tracer| Modifiers_impl::rule_parser(state, tracer, cache))
    }
    impl PegPosition for Modifiers {
        fn position(&self) -> &std::ops::Range<usize> {
            &self.position
        }
    }
    mod ChoiceNode_impl {
        use super::*;
        mod part_1 {
            use super::*;
            mod closure {
                use super::*;
            }
            #[inline(always)]
            pub fn parse<'a>(
                state: ParseState<'a>,
                tracer: impl ParseTracer,
                cache: &mut ParseCache<'a>,
            ) -> ParseResult<'a, Parsed> {
                let mut iterations: usize = 0;
                let mut state = state;
                let mut terms: Vec<TermStream> = Vec::new();
                loop {
                    match parse_Whitespace(state.clone(), tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_TermStream(state, tracer, cache))
                        .map_inner(|result| vec![result])
                    {
                        Ok(ParseOk { result: __result, state: new_state, .. }) => {
                            terms.extend(__result);
                            state = new_state;
                        }
                        Err(err) => {
                            state = state.record_error(err);
                            break;
                        }
                    }
                    iterations += 1;
                }
                Ok(ParseOk { result: terms, state })
            }
            pub type Parsed = Vec<TermStream>;
        }
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let ParseOk { state, .. } = parse_Whitespace(state.clone(), tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, '|'))
                .discard_result()
                .or_else(|err| Ok(ParseOk { result: (), state: state.record_error(err) }))?;
            let ParseOk { result: mut terms, state } = part_1::parse(state, tracer, cache)?;
            Ok(ParseOk { result: terms, state })
        }
        pub type Parsed = Vec<TermStream>;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::ChoiceNode> {
            let result = parse(state.clone(), tracer, cache)?
                .map_with_state(|r, new_state| super::ChoiceNode { terms: r, position: state.range_until(new_state) });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_ChoiceNode<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, ChoiceNode> {
        tracer.run_traced("ChoiceNode", state, |state, tracer| ChoiceNode_impl::rule_parser(state, tracer, cache))
    }
    impl PegPosition for ChoiceNode {
        fn position(&self) -> &std::ops::Range<usize> {
            &self.position
        }
    }
    mod ExprStream_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            mut state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            ChoiceHelper::new(state)
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_Prefix(state, tracer, cache))
                        .map_inner(Parsed__override::Prefix)
                })
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_Suffix(state, tracer, cache))
                        .map_inner(Parsed__override::Suffix)
                })
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_Infix(state, tracer, cache))
                        .map_inner(Parsed__override::Infix)
                })
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_CharsetNode(state, tracer, cache))
                        .map_inner(Parsed__override::CharsetNode)
                })
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_StringLiteral(state, tracer, cache))
                        .map_inner(Parsed__override::StringLiteral)
                })
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_Identifier(state, tracer, cache))
                        .map_inner(Parsed__override::Identifier)
                })
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_Group(state, tracer, cache))
                        .map_inner(Parsed__override::Group)
                })
                .end()
        }
        pub type Parsed = Parsed__override;
        use super::ExprStream as Parsed__override;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::ExprStream> {
            let result = parse(state, tracer, cache)?;
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_ExprStream<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, ExprStream> {
        tracer.run_traced("ExprStream", state, |state, tracer| ExprStream_impl::rule_parser(state, tracer, cache))
    }
    #[inline]
    pub(super) fn parse_Prefix<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, Prefix> {
        if let Ok(result) = parse_character_literal(state.clone(), '^') {
            return Ok(result);
        }
        if let Ok(result) = parse_character_literal(state.clone(), '!') {
            return Ok(result);
        }
        Err(state.report_error(ParseErrorSpecifics::ExpectedCharacterClass { name: "Prefix" }))
    }
    #[inline]
    pub(super) fn parse_Suffix<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, Suffix> {
        if let Ok(result) = parse_character_literal(state.clone(), '+') {
            return Ok(result);
        }
        if let Ok(result) = parse_character_literal(state.clone(), '*') {
            return Ok(result);
        }
        if let Ok(result) = parse_character_literal(state.clone(), '?') {
            return Ok(result);
        }
        Err(state.report_error(ParseErrorSpecifics::ExpectedCharacterClass { name: "Suffix" }))
    }
    #[inline]
    pub(super) fn parse_Infix<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, Infix> {
        if let Ok(result) = parse_character_literal(state.clone(), '|') {
            return Ok(result);
        }
        if let Ok(result) = parse_character_literal(state.clone(), ':') {
            return Ok(result);
        }
        if let Ok(result) = parse_character_literal(state.clone(), '~') {
            return Ok(result);
        }
        Err(state.report_error(ParseErrorSpecifics::ExpectedCharacterClass { name: "Infix" }))
    }
    mod Arguments_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, '('))
                .discard_result()?;
            let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, ')'))
                .discard_result()?;
            Ok(ParseOk { result: (), state })
        }
        pub type Parsed = ();
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::Arguments> {
            let result = parse(state.clone(), tracer, cache)?
                .map_with_state(|r, new_state| super::Arguments { position: state.range_until(new_state) });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_Arguments<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, Arguments> {
        tracer.run_traced("Arguments", state, |state, tracer| Arguments_impl::rule_parser(state, tracer, cache))
    }
    impl PegPosition for Arguments {
        fn position(&self) -> &std::ops::Range<usize> {
            &self.position
        }
    }
    mod Typing_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let ParseOk { state, .. } = ChoiceHelper::new(state)
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_string_literal(state, "->"))
                        .discard_result()
                })
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_character_literal(state, ':'))
                        .discard_result()
                })
                .end()?;
            let ParseOk { result: id, state } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_Identifier(state, tracer, cache))?;
            Ok(ParseOk { result: id, state })
        }
        pub type Parsed = Identifier;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::Typing> {
            let result = parse(state.clone(), tracer, cache)?
                .map_with_state(|r, new_state| super::Typing { id: r, position: state.range_until(new_state) });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_Typing<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, Typing> {
        tracer.run_traced("Typing", state, |state, tracer| Typing_impl::rule_parser(state, tracer, cache))
    }
    impl PegPosition for Typing {
        fn position(&self) -> &std::ops::Range<usize> {
            &self.position
        }
    }
    mod Group_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, '('))
                .discard_result()?;
            let ParseOk { result: body, state } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_ChoiceNode(state, tracer, cache))?;
            let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, ')'))
                .discard_result()?;
            Ok(ParseOk { result: body, state })
        }
        pub type Parsed = ChoiceNode;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::Group> {
            let result = parse(state.clone(), tracer, cache)?
                .map_with_state(|r, new_state| super::Group { body: r, position: state.range_until(new_state) });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_Group<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, Group> {
        tracer.run_traced("Group", state, |state, tracer| Group_impl::rule_parser(state, tracer, cache))
    }
    impl PegPosition for Group {
        fn position(&self) -> &std::ops::Range<usize> {
            &self.position
        }
    }
    mod StringLiteral_impl {
        use super::*;
        mod choice_0 {
            use super::*;
            mod part_1 {
                use super::*;
                mod closure {
                    use super::*;
                    mod part_0 {
                        use super::*;
                        mod negative_lookahead {
                            use super::*;
                            #[inline(always)]
                            pub fn parse<'a>(
                                state: ParseState<'a>,
                                tracer: impl ParseTracer,
                                cache: &mut ParseCache<'a>,
                            ) -> ParseResult<'a, Parsed> {
                                parse_character_literal(state, '"').discard_result()
                            }
                            pub type Parsed = ();
                        }
                        #[inline(always)]
                        pub fn parse<'a>(
                            state: ParseState<'a>,
                            tracer: impl ParseTracer,
                            cache: &mut ParseCache<'a>,
                        ) -> ParseResult<'a, Parsed> {
                            match negative_lookahead::parse(state.clone(), tracer, cache) {
                                Ok(_) => Err(state.report_error(ParseErrorSpecifics::NegativeLookaheadFailed)),
                                Err(_) => Ok(ParseOk { result: (), state }),
                            }
                        }
                        pub type Parsed = ();
                    }
                    #[inline(always)]
                    pub fn parse<'a>(
                        state: ParseState<'a>,
                        tracer: impl ParseTracer,
                        cache: &mut ParseCache<'a>,
                    ) -> ParseResult<'a, Parsed> {
                        let ParseOk { state, .. } = part_0::parse(state, tracer, cache)?;
                        let ParseOk { result: mut body, state } =
                            parse_StringItem(state, tracer, cache).map_inner(|result| vec![result])?;
                        Ok(ParseOk { result: body, state })
                    }
                    pub type Parsed = Vec<StringItem>;
                }
                #[inline(always)]
                pub fn parse<'a>(
                    state: ParseState<'a>,
                    tracer: impl ParseTracer,
                    cache: &mut ParseCache<'a>,
                ) -> ParseResult<'a, Parsed> {
                    let mut iterations: usize = 0;
                    let mut state = state;
                    let mut body: Vec<StringItem> = Vec::new();
                    loop {
                        match closure::parse(state.clone(), tracer, cache) {
                            Ok(ParseOk { result: __result, state: new_state, .. }) => {
                                body.extend(__result);
                                state = new_state;
                            }
                            Err(err) => {
                                state = state.record_error(err);
                                break;
                            }
                        }
                        iterations += 1;
                    }
                    Ok(ParseOk { result: body, state })
                }
                pub type Parsed = Vec<StringItem>;
            }
            #[inline(always)]
            pub fn parse<'a>(
                state: ParseState<'a>,
                tracer: impl ParseTracer,
                cache: &mut ParseCache<'a>,
            ) -> ParseResult<'a, Parsed> {
                let ParseOk { state, .. } = parse_character_literal(state, '"').discard_result()?;
                let ParseOk { result: mut body, state } = part_1::parse(state, tracer, cache)?;
                let ParseOk { state, .. } = parse_character_literal(state, '"').discard_result()?;
                Ok(ParseOk { result: body, state })
            }
            pub type Parsed = Vec<StringItem>;
        }
        mod choice_1 {
            use super::*;
            mod part_1 {
                use super::*;
                mod closure {
                    use super::*;
                    mod part_0 {
                        use super::*;
                        mod negative_lookahead {
                            use super::*;
                            #[inline(always)]
                            pub fn parse<'a>(
                                state: ParseState<'a>,
                                tracer: impl ParseTracer,
                                cache: &mut ParseCache<'a>,
                            ) -> ParseResult<'a, Parsed> {
                                parse_character_literal(state, '\'').discard_result()
                            }
                            pub type Parsed = ();
                        }
                        #[inline(always)]
                        pub fn parse<'a>(
                            state: ParseState<'a>,
                            tracer: impl ParseTracer,
                            cache: &mut ParseCache<'a>,
                        ) -> ParseResult<'a, Parsed> {
                            match negative_lookahead::parse(state.clone(), tracer, cache) {
                                Ok(_) => Err(state.report_error(ParseErrorSpecifics::NegativeLookaheadFailed)),
                                Err(_) => Ok(ParseOk { result: (), state }),
                            }
                        }
                        pub type Parsed = ();
                    }
                    #[inline(always)]
                    pub fn parse<'a>(
                        state: ParseState<'a>,
                        tracer: impl ParseTracer,
                        cache: &mut ParseCache<'a>,
                    ) -> ParseResult<'a, Parsed> {
                        let ParseOk { state, .. } = part_0::parse(state, tracer, cache)?;
                        let ParseOk { result: mut body, state } =
                            parse_StringItem(state, tracer, cache).map_inner(|result| vec![result])?;
                        Ok(ParseOk { result: body, state })
                    }
                    pub type Parsed = Vec<StringItem>;
                }
                #[inline(always)]
                pub fn parse<'a>(
                    state: ParseState<'a>,
                    tracer: impl ParseTracer,
                    cache: &mut ParseCache<'a>,
                ) -> ParseResult<'a, Parsed> {
                    let mut iterations: usize = 0;
                    let mut state = state;
                    let mut body: Vec<StringItem> = Vec::new();
                    loop {
                        match closure::parse(state.clone(), tracer, cache) {
                            Ok(ParseOk { result: __result, state: new_state, .. }) => {
                                body.extend(__result);
                                state = new_state;
                            }
                            Err(err) => {
                                state = state.record_error(err);
                                break;
                            }
                        }
                        iterations += 1;
                    }
                    Ok(ParseOk { result: body, state })
                }
                pub type Parsed = Vec<StringItem>;
            }
            #[inline(always)]
            pub fn parse<'a>(
                state: ParseState<'a>,
                tracer: impl ParseTracer,
                cache: &mut ParseCache<'a>,
            ) -> ParseResult<'a, Parsed> {
                let ParseOk { state, .. } = parse_character_literal(state, '\'').discard_result()?;
                let ParseOk { result: mut body, state } = part_1::parse(state, tracer, cache)?;
                let ParseOk { state, .. } = parse_character_literal(state, '\'').discard_result()?;
                Ok(ParseOk { result: body, state })
            }
            pub type Parsed = Vec<StringItem>;
        }
        #[inline(always)]
        pub fn parse<'a>(
            mut state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            ChoiceHelper::new(state)
                .choice(|state| choice_0::parse(state.clone(), tracer, cache))
                .choice(|state| choice_1::parse(state.clone(), tracer, cache))
                .end()
        }
        pub type Parsed = Vec<StringItem>;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::StringLiteral> {
            let result = parse(state.clone(), tracer, cache)?
                .map_with_state(|r, new_state| super::StringLiteral { body: r, position: state.range_until(new_state) });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_StringLiteral<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, StringLiteral> {
        tracer.run_traced("StringLiteral", state, |state, tracer| StringLiteral_impl::rule_parser(state, tracer, cache))
    }
    impl PegPosition for StringLiteral {
        fn position(&self) -> &std::ops::Range<usize> {
            &self.position
        }
    }
    mod StringItem_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            mut state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            ChoiceHelper::new(state)
                .choice(|state| parse_StringEscaped(state, tracer, cache).map_inner(Parsed__override::StringEscaped))
                .choice(|state| parse_CharOne(state, tracer, cache).map_inner(Parsed__override::CharOne))
                .end()
        }
        pub type Parsed = Parsed__override;
        use super::StringItem as Parsed__override;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::StringItem> {
            let result = parse(state, tracer, cache)?;
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_StringItem<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, StringItem> {
        tracer.run_traced("StringItem", state, |state, tracer| StringItem_impl::rule_parser(state, tracer, cache))
    }
    mod StringEscaped_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, '\\'))
                .discard_result()?;
            let ParseOk { result: char, state } =
                parse_Whitespace(state, tracer, cache).and_then(|ParseOk { state, .. }| parse_char(state, tracer, cache))?;
            Ok(ParseOk { result: char, state })
        }
        pub type Parsed = char;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::StringEscaped> {
            let result = parse(state, tracer, cache)?.map(|r| super::StringEscaped { char: r });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_StringEscaped<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, StringEscaped> {
        tracer.run_traced("StringEscaped", state, |state, tracer| StringEscaped_impl::rule_parser(state, tracer, cache))
    }
    mod CharsetNode_impl {
        use super::*;
        mod part_2 {
            use super::*;
            mod closure {
                use super::*;
            }
            #[inline(always)]
            pub fn parse<'a>(
                state: ParseState<'a>,
                tracer: impl ParseTracer,
                cache: &mut ParseCache<'a>,
            ) -> ParseResult<'a, Parsed> {
                let mut iterations: usize = 0;
                let mut state = state;
                let mut items: Vec<CharItem> = Vec::new();
                loop {
                    match parse_Whitespace(state.clone(), tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_CharItem(state, tracer, cache))
                        .map_inner(|result| vec![result])
                    {
                        Ok(ParseOk { result: __result, state: new_state, .. }) => {
                            items.extend(__result);
                            state = new_state;
                        }
                        Err(err) => {
                            state = state.record_error(err);
                            break;
                        }
                    }
                    iterations += 1;
                }
                Ok(ParseOk { result: items, state })
            }
            pub type Parsed = Vec<CharItem>;
        }
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, '['))
                .discard_result()?;
            let ParseOk { result: neg, state } = parse_Whitespace(state.clone(), tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_CharsetNeg(state, tracer, cache))
                .map_inner(Some)
                .or_else(|err| Ok(ParseOk { result: Default::default(), state: state.record_error(err) }))?;
            let ParseOk { result: mut items, state } = part_2::parse(state, tracer, cache)?;
            let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, ']'))
                .discard_result()?;
            Ok(ParseOk { result: Parsed { neg, items }, state })
        }
        pub struct Parsed {
            pub neg: Option<CharsetNeg>,
            pub items: Vec<CharItem>,
        }
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::CharsetNode> {
            let result = parse(state.clone(), tracer, cache)?.map_with_state(|r, new_state| super::CharsetNode {
                neg: r.neg,
                items: r.items,
                position: state.range_until(new_state),
            });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_CharsetNode<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, CharsetNode> {
        tracer.run_traced("CharsetNode", state, |state, tracer| CharsetNode_impl::rule_parser(state, tracer, cache))
    }
    impl PegPosition for CharsetNode {
        fn position(&self) -> &std::ops::Range<usize> {
            &self.position
        }
    }
    mod CharsetNeg_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, '^'))
                .discard_result()
        }
        pub type Parsed = ();
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::CharsetNeg> {
            let result = parse(state, tracer, cache)?.map(|r| super::CharsetNeg {});
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_CharsetNeg<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, CharsetNeg> {
        tracer.run_traced("CharsetNeg", state, |state, tracer| CharsetNeg_impl::rule_parser(state, tracer, cache))
    }
    mod CharItem_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            mut state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            ChoiceHelper::new(state)
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_CharRange(state, tracer, cache))
                        .map_inner(Parsed__override::CharRange)
                })
                .choice(|state| {
                    parse_Whitespace(state, tracer, cache)
                        .and_then(|ParseOk { state, .. }| parse_CharOne(state, tracer, cache))
                        .map_inner(Parsed__override::CharOne)
                })
                .end()
        }
        pub type Parsed = Parsed__override;
        use super::CharItem as Parsed__override;
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::CharItem> {
            let result = parse(state, tracer, cache)?;
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_CharItem<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, CharItem> {
        tracer.run_traced("CharItem", state, |state, tracer| CharItem_impl::rule_parser(state, tracer, cache))
    }
    mod CharRange_impl {
        use super::*;
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let ParseOk { result: start, state } =
                parse_Whitespace(state, tracer, cache).and_then(|ParseOk { state, .. }| parse_char(state, tracer, cache))?;
            let ParseOk { state, .. } = parse_Whitespace(state, tracer, cache)
                .and_then(|ParseOk { state, .. }| parse_character_literal(state, '-'))
                .discard_result()?;
            let ParseOk { result: end, state } =
                parse_Whitespace(state, tracer, cache).and_then(|ParseOk { state, .. }| parse_char(state, tracer, cache))?;
            Ok(ParseOk { result: Parsed { start, end }, state })
        }
        pub struct Parsed {
            pub start: char,
            pub end: char,
        }
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, super::CharRange> {
            let result = parse(state.clone(), tracer, cache)?.map_with_state(|r, new_state| super::CharRange {
                start: r.start,
                end: r.end,
                position: state.range_until(new_state),
            });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_CharRange<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, CharRange> {
        tracer.run_traced("CharRange", state, |state, tracer| CharRange_impl::rule_parser(state, tracer, cache))
    }
    impl PegPosition for CharRange {
        fn position(&self) -> &std::ops::Range<usize> {
            &self.position
        }
    }
    #[inline]
    pub(super) fn parse_CharOne<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, CharOne> {
        if let Ok(result) = parse_char(state.clone(), tracer, cache) {
            return Ok(result);
        }
        Err(state.report_error(ParseErrorSpecifics::ExpectedCharacterClass { name: "CharOne" }))
    }
    mod Identifier_impl {
        use super::*;
        mod part_1 {
            use super::*;
            mod closure {
                use super::*;
            }
            #[inline(always)]
            pub fn parse<'a>(
                state: ParseState<'a>,
                tracer: impl ParseTracer,
                cache: &mut ParseCache<'a>,
            ) -> ParseResult<'a, Parsed> {
                let mut iterations: usize = 0;
                let mut state = state;
                loop {
                    match parse_XID_CONTINUE(state.clone(), tracer, cache).discard_result() {
                        Ok(ParseOk { result: __result, state: new_state, .. }) => {
                            state = new_state;
                        }
                        Err(err) => {
                            state = state.record_error(err);
                            break;
                        }
                    }
                    iterations += 1;
                }
                Ok(ParseOk { result: (), state })
            }
            pub type Parsed = ();
        }
        #[inline(always)]
        pub fn parse<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Parsed> {
            let ParseOk { state, .. } = ChoiceHelper::new(state)
                .choice(|state| parse_XID_START(state, tracer, cache).discard_result())
                .choice(|state| parse_character_literal(state, '_').discard_result())
                .end()?;
            let ParseOk { state, .. } = part_1::parse(state, tracer, cache)?;
            Ok(ParseOk { result: (), state })
        }
        pub type Parsed = ();
        #[inline(always)]
        pub fn rule_parser<'a>(
            state: ParseState<'a>,
            tracer: impl ParseTracer,
            cache: &mut ParseCache<'a>,
        ) -> ParseResult<'a, Identifier> {
            let result = parse(state.clone(), tracer, cache)?.map_with_state(|_, new_state| {
                let string = state.slice_until(new_state).to_string();
                Identifier { string, position: state.range_until(new_state) }
            });
            Ok(result)
        }
    }
    #[inline]
    pub(super) fn parse_Identifier<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, Identifier> {
        tracer.run_traced("Identifier", state, |state, tracer| Identifier_impl::rule_parser(state, tracer, cache))
    }
    impl PegPosition for Identifier {
        fn position(&self) -> &std::ops::Range<usize> {
            &self.position
        }
    }
    #[inline]
    pub(super) fn parse_XID_START<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, XID_START> {
        if let Some(c) = state.s().chars().next() {
            if !unicode_xid::UnicodeXID::is_xid_start(c) {
                return Err(state.report_error(ParseErrorSpecifics::ExpectedCharacterClass { name: "XID_START" }));
            }
        }
        else {
            return Err(state.report_error(ParseErrorSpecifics::ExpectedCharacterClass { name: "XID_START" }));
        }
        if let Ok(result) = parse_char(state.clone(), tracer, cache) {
            return Ok(result);
        }
        Err(state.report_error(ParseErrorSpecifics::ExpectedCharacterClass { name: "XID_START" }))
    }
    #[inline]
    pub(super) fn parse_XID_CONTINUE<'a>(
        state: ParseState<'a>,
        tracer: impl ParseTracer,
        cache: &mut ParseCache<'a>,
    ) -> ParseResult<'a, XID_CONTINUE> {
        if let Some(c) = state.s().chars().next() {
            if !unicode_xid::UnicodeXID::is_xid_continue(c) {
                return Err(state.report_error(ParseErrorSpecifics::ExpectedCharacterClass { name: "XID_CONTINUE" }));
            }
        }
        else {
            return Err(state.report_error(ParseErrorSpecifics::ExpectedCharacterClass { name: "XID_CONTINUE" }));
        }
        if let Ok(result) = parse_char(state.clone(), tracer, cache) {
            return Ok(result);
        }
        Err(state.report_error(ParseErrorSpecifics::ExpectedCharacterClass { name: "XID_CONTINUE" }))
    }
}
