@export
@position
Program = {statement:Statement} $;

Statement =
    @:DefineStatement [EOS]
  | @:EmptyStatement
  ;

EmptyStatement = EOS;

@string
@no_skip_ws
EOS = ';;' | ';';

@position
DefineStatement = define:DEFINE modifiers:Modifiers symbol:Identifier '{' body:Choice '}';

@string
@no_skip_ws
DEFINE = 'def!' | 'def';

@position
Modifiers = {id:Identifier (!'{')};

@position
Choice = [['|'] terms:Term {"|" terms:Term}];

@position
Term = {prefix:Prefix} node:Node {suffix:Suffix};

@char
Prefix = '^';

@char
Suffix = '+' | '*' | '?';

Node =
    @:Group |
    @:Charset |
    @:StringLiteral
    ;
Group = "(" body:Choice ")";
Optional = body:Choice "?";

@no_skip_ws
StringLiteral =
    '"' {!'"' body:StringItem } '"' |
    "'" {!"'" body:StringItem } "'"
    ;

@string
@no_skip_ws
StringItem = '\\' char | char;

@position
Charset = '[' CharRange ']';
CharItem =
    @:CharRange |
    ;
CharRange = char '-' char;


@position
Identifier = identifier:IDENTIFIER;

@string
@no_skip_ws
IDENTIFIER = {'a'..'z' | 'A'..'Z' | '_' | '0'..'9'}+;
