@position
ProgramNode = statements:StatementNode;

@position
StatementNode = (DefineStatementNode EOSNode);

@position
EmptyStatementNode = EOSNode;

@position
MacroCallsNode = MacroCallNode;

@position
MacroCallNode = ("#" macros:MacroNode) | ("#" "[" macros:MacroNode "]");

@position
MacroNode = (IdentifierNode ArgumentsNode);

@position
ArgumentsNode = ("(" ArgumentValueNode ")");

@position
ArgumentValueNode = BooleanNode;

@position
DefineStatementNode = (MacroCallsNode DefineNode ModifiersNode symbol:IdentifierNode ArgumentsNode);

@position @string
DefineNode = "def" | "class" | "union" | "structure" | "struct" | "enumerate" | "enum";

@position
TypingNode = ("->" IdentifierNode);

@position
ChoiceNode = "|";

@position
ExprStreamNode = PrefixNode | InfixNode | SuffixNode | CharsetNodeNode | StringLiteralNode | IdentifierNode | GroupNode;

@position @string
PrefixNode = "^" | "!";

@position @string
InfixNode = "|" | ":" | "~";

@position @string
SuffixNode = "+" | "*" | "?";

@position
GroupNode = ("(" ChoiceNode ")");

@position
ModifiersNode = ModifierNode;

@position
ModifierNode = IdentifierNode;

@position @string
BooleanNode = "true" | "false";

@position
IdentifierNode = ("XID_START" | "_" "XID_CONTINUE");

@position @string
EOSNode = ";";

