use crate::position::Position;

/// A token generated by a `Parser`.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub enum Token<'i, R> {
    /// The starting `Position` of a matched `Rule`
    Start {
        /// matched rule
        rule: R,
        /// starting position
        pos: Position<'i>,
    },
    /// The ending `Position` of a matched `Rule`
    End {
        /// matched rule
        rule: R,
        /// ending position
        pos: Position<'i>,
    },
}
